# Generated by Django 5.0 on 2025-01-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('preferences', models.CharField(blank=True, max_length=255, null=True, verbose_name='PReferences')),
                ('notifications', models.BooleanField(default=False, verbose_name='Notification Preference')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10, verbose_name='OTP')),
            ],
        ),
        migrations.CreateModel(
            name='SmsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('alert', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alert')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
