# Generated by Django 5.0 on 2025-01-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_contactpreference_isauthenticated_delete_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPreference',
        ),
    ]
