# Generated by Django 5.0 on 2025-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_delete_contactpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isauthenticated',
            name='index',
        ),
        migrations.RemoveField(
            model_name='isauthenticated',
            name='otp',
        ),
        migrations.AddField(
            model_name='isauthenticated',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isauthenticated',
            name='isverified',
            field=models.BooleanField(default=False, verbose_name='Is Authenticated?'),
        ),
    ]
