# Generated by Django 5.1.7 on 2025-03-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_isauthenticated_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpreferences',
            name='preferences',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preferences'),
        ),
        migrations.CreateModel(
            name='PushNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Push Notifications Enabled')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Verification')),
            ],
        ),
    ]
