# Generated by Django 5.1.7 on 2025-03-11 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='First Name')),
                ('relation', models.CharField(max_length=18, verbose_name='Relation')),
                ('contact', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='nominee', to=settings.AUTH_USER_MODEL, verbose_name='nominee')),
            ],
        ),
    ]
