# Generated by Django 5.1.7 on 2025-03-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomminee', '0002_alter_nominee_contact_alter_nominee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
    ]
