# Generated by Django 5.0 on 2024-09-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=300)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
    ]
