# Generated by Django 5.0 on 2025-02-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_contactus_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
