# Generated by Django 5.0 on 2025-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0003_delete_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=300)),
                ('message', models.TextField(max_length=400)),
                ('senderid', models.IntegerField(editable=False)),
            ],
        ),
    ]
