# Generated by Django 5.1.7 on 2025-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='senderid',
        ),
        migrations.AddField(
            model_name='support',
            name='sendername',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sender_Name'),
        ),
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
