# Generated by Django 5.0 on 2024-10-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAppModel',
        ),
    ]
