# Generated by Django 5.0 on 2025-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpreference',
            name='emailnotification',
            field=models.CharField(choices=[('all', 'All'), ('important', 'Important Only'), ('none', 'None')], default=None, max_length=30, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='contactpreference',
            name='smsnotification',
            field=models.CharField(choices=[('all', 'All'), ('important', 'Important Only'), ('none', 'None')], default=None, max_length=30, verbose_name='SMS Notifications'),
        ),
    ]
