# Generated by Django 5.0 on 2025-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_alter_contactpreference_emailnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpreference',
            name='emailnotification',
            field=models.CharField(choices=[('all', 'All'), ('important', 'Important Only'), ('none', 'None')], default='none', max_length=30, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='contactpreference',
            name='smsnotification',
            field=models.CharField(choices=[('all', 'All'), ('important', 'Important Only'), ('none', 'None')], default='none', max_length=30, verbose_name='SMS Notifications'),
        ),
    ]
