# Generated by Django 5.0 on 2025-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/', verbose_name='user_profile'),
        ),
    ]
