# Generated by Django 5.1.7 on 2025-03-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_alter_contactpreference_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
