# Generated by Django 5.0 on 2025-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_subscribed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
