# Generated by Django 5.0 on 2025-03-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accbalance',
        ),
    ]
