# Generated by Django 5.0 on 2025-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0004_alter_accbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accbalance',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=12),
        ),
    ]
