# Generated by Django 5.0 on 2025-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0005_alter_accbalance_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
