# Generated by Django 5.0 on 2025-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0006_transactionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
