# Generated by Django 5.0 on 2025-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0007_delete_transactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed')], max_length=13, verbose_name='status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=50, verbose_name='sender')),
                ('receiver', models.CharField(max_length=50, verbose_name='receiver')),
            ],
        ),
    ]
