# Generated by Django 5.1.7 on 2025-03-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0008_transactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_balance',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
