# Generated by Django 5.1.7 on 2025-03-08 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0009_remove_statement_transaction_remove_statement_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed')], max_length=13, verbose_name='status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=50, verbose_name='sender')),
                ('receiver', models.CharField(max_length=50, verbose_name='receiver')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.PositiveIntegerField(editable=False, unique=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('receiver_balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactons_as_receiver', to='fundtransfer.accbalance')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender_balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactons_as_sender', to='fundtransfer.accbalance')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='statements', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='fundtransfer.transaction')),
            ],
        ),
    ]
