# Generated by Django 5.1.7 on 2025-03-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundtransfer', '0010_transactionlog_transaction_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionid',
        ),
    ]
