# Generated by Django 5.0 on 2024-09-20 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='securityquestion',
            name='cust',
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Address Info '),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contact '),
        ),
        migrations.AddField(
            model_name='customerpersonalinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal Details'),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Security Question'),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
