# Generated by Django 5.0 on 2024-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_addressinfo_user_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpersonalinfo',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Income'),
        ),
    ]
