# Generated by Django 5.0 on 2025-01-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_customerpersonalinfo_annual_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsAuthenticated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isverified', models.BooleanField(default=False, verbose_name='Is Authenticated  ?')),
                ('otp', models.CharField(max_length=6, verbose_name='Otp')),
            ],
        ),
    ]
