# Generated by Django 5.0 on 2025-01-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_accountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Account Status'),
        ),
    ]
