# Generated by Django 5.0 on 2025-02-25 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_accountdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsAuthenticated',
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Account Number', unique=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_status',
            field=models.CharField(default='active', max_length=20, verbose_name='Account Status'),
        ),
    ]
