# Generated by Django 5.0 on 2025-03-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_delete_isauthenticated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='account_balance',
        ),
    ]
