# Generated by Django 5.0 on 2025-03-03 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_userlogin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='CustomUserLogin',
        ),
    ]
