# Generated by Django 5.0 on 2025-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_rename_userlogin_customuserlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.UUIDField(db_index=True, editable=False, help_text='Account Number', unique=True),
        ),
    ]
