# Generated by Django 5.0 on 2025-03-05 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_addressinfo_user_alter_contact_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_details', related_query_name='account_details', to=settings.AUTH_USER_MODEL, verbose_name='Account Details'),
        ),
        migrations.AlterField(
            model_name='addressinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='address_info', to=settings.AUTH_USER_MODEL, verbose_name='Address Info'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='contact', to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='customuserlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customlogin', related_query_name='customlogin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='security_question', to=settings.AUTH_USER_MODEL, verbose_name='Security Question'),
        ),
    ]
