# Generated by Django 5.1.7 on 2025-03-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_addressinfo_user_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDetails',
        ),
    ]
