# Generated by Django 5.1.7 on 2025-03-08 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_delete_accountdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.UUIDField(db_index=True, editable=False, help_text='Account Number', unique=True)),
                ('account_status', models.CharField(default='active', max_length=20, verbose_name='Account Status')),
                ('bankname', models.CharField(max_length=15, verbose_name='Bank Name')),
                ('bankbranch', models.CharField(default='Saiful Branch', max_length=60, verbose_name='Bank Branch')),
                ('bankadd', models.CharField(default='Saiful,Vijapur Road, Solapur,Maharastra', max_length=60, verbose_name='Bank Address')),
                ('ifsc', models.CharField(default='LACF0001234', max_length=11, verbose_name='IFSC CODE')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to=settings.AUTH_USER_MODEL, verbose_name='Account Details')),
            ],
        ),
    ]
