# Generated by Django 5.1.7 on 2025-03-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_addressinfo_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pincode'),
        ),
    ]
