# Generated by Django 5.1.7 on 2025-03-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_addressinfo_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserLogin',
        ),
    ]
