# Generated by Django 5.1.7 on 2025-04-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_alter_accountdetails_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='bankname',
            field=models.CharField(default='Laxmi Cheat Fund', max_length=20, verbose_name='Bank Name'),
        ),
    ]
